### ISSUE TITLE
Issue: Hardcoded config path and missing configuration file for VMamba pretrained models

### ISSUE THREAD

**Issue by jonathanmcgillivray** [canyagmur/XPoint#2]
### Description
When attempting to use the model with attention and  `pretrained=False`, I encountered an issue where the code tries to load a config file from a hardcoded local path that doesn't exist in the repository:

In xpoint/models/XPoint.py, line 455
mypath = "/home/wasproject/Desktop/Can/XPoint/model_weights/encoder-pretrained/vmamba-imagenet/vssm_tiny_segmentation_special/vssm_tiny.yaml"

### Problem
The required config file is not included in the repository and there is no documentation about what values to use to be able to load the pretrained model weights.

### Solution
Would it be possible to include this configuration file in the repository?

**Comment by ibrahim-azista** [comment]
The YAML file you're asking about can be found [here](https://github.com/canyagmur/XPoint?tab=readme-ov-file#pre-trained-models); it was mentioned in the README.md file under the "Pre-trained Models" section.

**Comment by canyagmur** [comment]
First of all, thank you for your interest in our work, and I apologize for the delayed response—I’ve been a bit busy this week.

The issue has been resolved in the latest commit. Please pull the latest changes from the repository, and this should address the problem you encountered.

If you face any further issues or have additional suggestions, please don’t hesitate to reach out. Your feedback is greatly appreciated and helps us.

Best regards,
-Can

**Comment by jonathanmcgillivray** [comment]
Thank you for the quick fix and for maintaining this repository! I can confirm that after pulling the latest changes, I'm now able to run the model successfully.

I'm looking forward to experimenting with the model and testing its performance on an aerial RGB/IR dataset. Really appreciate your work on this project!

Best Regards
Jono
